# Configuration of the daisy app
daisy:
  # Configuration of APIs
  apis:
    # Configuration of the icanhazdadjoke API
    icanhazdadjoke:
      # Host of the API
      host: icanhazdadjoke.com

      # Path of the API
      path: null

      # Port of the API
      port: null

      # Scheme of the API
      scheme: https

    # Configuration of the mantis API
    mantis:
      # Host of the API
      host: mantis.mantis.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10800

      # Scheme of the API
      scheme: http

  # Enable debug mode
  debug: true

  # Configuration of the server
  server:
    # Port to listen on
    port: 10810

# Configuration of the service
service:
  # Port to listen on
  port: 10810
