# Configuration of the daisy app
daisy:
  # Configuration of APIs
  apis:
    # Configuration of the icanhazdadjoke API
    icanhazdadjoke:
      # Host of the API
      host: icanhazdadjoke.com

      # Path of the API
      path: null

      # Port of the API
      port: null

      # Scheme of the API
      scheme: https

    # Configuration of the mantis API
    mantis:
      # Host of the API
      host: mantis.mantis.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10800

      # Scheme of the API
      scheme: http

  # Enable debug mode
  debug: true

  # Configuration related to identity
  identity:
    # Configuration of users
    users:
      # Configuration of the debug user
      debug:
        # Identifier of the debug user
        id: debug

        # Traits of the debug user
        traits:
          # Locales of the debug user
          locales:
            # Preferred locale of the debug user
            preferred: null

          # Names of the debug user
          names:
            # Display name of the debug user
            display: Debug User

          # Pictures of the debug user
          pictures:
            # Profile picture of the debug user
            profile:
              # Profile picture URL of the debug user
              url: null

  # Configuration of the server
  server:
    # Port to listen on
    port: 10810

# Configuration of the service
service:
  # Port to listen on
  port: 10810
