# Configuration of the database
database:
  # Configuration of the server
  server:
    # Ports to listen on
    ports:
      # Port to listen on for S3 connections
      s3: 40000

      # Port to listen on for web console traffic
      web: 40001

  # URLs configuration
  urls:
    # Public URL of the web interface
    web: http://localhost:40001

  # Credentials for the database
  credentials:
    # Credentials for the admin user
    admin:
      # Username of the admin user
      user: admin

      # Password of the admin user
      password: password

    # Credentials for the readonly user
    readonly:
      # Username of the readonly user
      user: readonly

      # Password of the readonly user
      password: password

    # Credentials for the readwrite user
    readwrite:
      # Username of the readwrite user
      user: readwrite

      # Password of the readwrite user
      password: password

  # Buckets configuration
  buckets:
    # Name of the bucket where raw media files are stored
    media: media

    # Name of the bucket where metadata is stored
    metadata: metadata

# Configuration of the service
service:
  # Ports to listen on
  ports:
    # Port to listen on for S3 connections
    s3: 40000

    # Port to listen on for web console traffic
    web: 40001
