# Configuration of the poppy app
poppy:
  # Configuration of APIs
  apis:
    # Configuration of the beaver API
    beaver:
      # Host of the API
      host: beaver.beaver.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10500

      # Scheme of the API
      scheme: http

    # Configuration of the icanhazdadjoke API
    icanhazdadjoke:
      # Host of the API
      host: icanhazdadjoke.com

      # Path of the API
      path: null

      # Port of the API
      port: null

      # Scheme of the API
      scheme: https

    # Configuration of the loris API
    loris:
      # Host of the API
      host: loris.loris.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10400

      # Scheme of the API
      scheme: http

    # Configuration of the octopus API
    octopus:
      # Host of the API
      host: octopus.octopus.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10300

      # Scheme of the API
      scheme: http

    # Configuration of the whip API
    whip:
      # Host of the API
      host: loris.loris.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10401

      # Scheme of the API
      scheme: http

  # Enable debug mode
  debug: true

  # Configuration of the server
  server:
    # Port to listen on
    port: 10410

  # Configuration of SRT servers
  srt:
    # Configuration of the octopus server
    octopus:
      # Host of the server
      host: octopus.octopus.svc.cluster.local

      # Port of the server
      port: 10300

# Configuration of the service
service:
  # Port to listen on
  port: 10410
