# Version of Helm this chart is compatible with
apiVersion: v2

# Version of the chart itself
version: "0.10.2"

# Version of the service provided by this chart
appVersion: "0.20.0"

# Name of the chart
name: octopus

# A short description of the chart
description: Broadcast streaming gate 🚧

# Home page of the service
home: https://radio-aktywne.github.io/octopus

# Source code repository of the service
sources:
  - https://github.com/radio-aktywne/octopus
