# Configuration of the orchid app
orchid:
  # Configuration of APIs
  apis:
    # Configuration of the falcon API
    falcon:
      # Host of the API
      host: falcon.falcon.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 20100

      # Scheme of the API
      scheme: http

    # Configuration of the icanhazdadjoke API
    icanhazdadjoke:
      # Host of the API
      host: icanhazdadjoke.com

      # Path of the API
      path: null

      # Port of the API
      port: null

      # Scheme of the API
      scheme: https

  # Enable debug mode
  debug: true

  # Configuration of OIDC Identity Providers
  oidc:
    # Configuration of Google IdP
    google:
      # Domain of the Google organization
      domain: null

  # Configuration of secrets
  secrets:
    # Shared secret containing 32 characters
    shared: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  # Configuration of the server
  server:
    # Port to listen on
    port: 20120

  # Configuration of the URLs
  urls:
    # Configuration of the crocus URL
    crocus:
      # Host of the URL
      host: localhost

      # Path of the URL
      path: null

      # Port of the URL
      port: 20020

      # Scheme of the URL
      scheme: http

    # Configuration of the falcon URL
    falcon:
      # Host of the URL
      host: localhost

      # Path of the URL
      path: null

      # Port of the URL
      port: 20100

      # Scheme of the URL
      scheme: http

# Configuration of the service
service:
  # Port to listen on
  port: 20120
