# Version of Helm this chart is compatible with
apiVersion: v2

# Version of the chart itself
version: "0.7.1"

# Version of the application provided by this chart
appVersion: "0.11.0"

# Name of the chart
name: emishows

# A short description of the chart
description: Emission shows 🎭

# Home page of the app
home: https://radio-aktywne.github.io/app-emishows

# Source code repository of the app
sources:
  - https://github.com/radio-aktywne/app-emishows
