# Configuration of the app
app:
  # Port to listen on
  port: 35000

  # Database configuration
  database:
    # Host of the database
    host: emishows-db.emishows-db.svc.cluster.local

    # Port of the database
    port: 34000

    # Password to authenticate with
    password: password

  # Emitimes configuration
  emitimes:
    # Host of the emitimes service
    host: emitimes.emitimes.svc.cluster.local

    # Port of the emitimes service
    port: 36000

    # User to authenticate with
    user: user

    # Password to authenticate with
    password: password

    # Calendar to use
    calendar: emitimes

# Configuration of the service
service:
  # Port to listen on
  port: 35000
