# Configuration of the app
app:
  # Configuration of the server
  server:
    # Port to listen on
    port: 38000

  # Configuration of the emirecords service
  emirecords:
    # Configuration of the HTTP API of the emirecords service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emirecords.emirecords.svc.cluster.local

      # Port of the HTTP API
      port: 31000

      # Path of the HTTP API
      path: ""

  # Configuration of the HTTP API of the emishows service
  emishows:
    # Configuration of the HTTP API of the emishows service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emishows.emishows.svc.cluster.local

      # Port of the HTTP API
      port: 35000

      # Path of the HTTP API
      path: ""

# Configuration of the service
service:
  # Port to listen on
  port: 38000
