# Configuration of the app
app:
  # Configuration of the server
  server:
    # Port to listen on
    port: 28000

  # Configuration of the emishows service
  emishows:
    # Configuration of the HTTP API of the emishows service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emishows.emishows.svc.cluster.local

      # Port of the HTTP API
      port: 35000

      # Path of the HTTP API
      path: ""

  # Configuration of the medialounge database
  medialounge:
    # Configuration of the S3 API of the medialounge database
    s3:
      # Whether to use secure connection with the S3 API
      secure: false

      # Host of the S3 API
      host: medialounge.medialounge.svc.cluster.local

      # Port of the S3 API
      port: 29000

      # User to authenticate with the S3 API
      user: readwrite

      # Password to authenticate with the S3 API
      password: password

# Configuration of the service
service:
  # Port to listen on
  port: 28000
