# Configuration of the loris service
loris:
  # Enable debug mode
  debug: true

  # Configuration of the server
  server:
    # Configuration of the server ports
    ports:
      # Port to listen for HTTP requests on
      http: 10400

      # Port to listen for RTP connections on
      rtp: 10402

      # Port to listen for WHIP requests on
      whip: 10401

  # Configuration of the streaming service
  streaming:
    # Configuration of the STUN server
    stun:
      # Host of the STUN server
      host: stun.l.google.com

      # Port of the STUN server
      port: 19302

    # Time after which a stream will be stopped if no connections are made
    timeout: PT1M

# Configuration of the service
service:
  # Configuration of the service ports
  ports:
    # Port to listen for HTTP requests on
    http: 10400

    # Port to listen for RTP connections on
    rtp: 10402

    # Port to listen for WHIP requests on
    whip: 10401
