# Version of Helm this chart is compatible with
apiVersion: v2

# Version of the chart itself
version: "0.1.0"

# Version of the application provided by this chart
appVersion: "0.1.0"

# Name of the chart
name: webtunes

# A short description of the chart
description: Emission playlists web UI 💽

# Home page of the app
home: https://radio-aktywne.github.io/app-webtunes

# Source code repository of the app
sources:
  - https://github.com/radio-aktywne/app-webtunes
