# Version of Helm this chart is compatible with
apiVersion: v2

# Version of the chart itself
version: "0.7.0"

# Version of the application provided by this chart
appVersion: "0.17.0"

# Name of the chart
name: emirecords

# A short description of the chart
description: Emission recording 🎥

# Home page of the app
home: https://radio-aktywne.github.io/app-emirecords

# Source code repository of the app
sources:
  - https://github.com/radio-aktywne/app-emirecords
