# Configuration of the app
app:
  # Configuration of the server
  server:
    # Ports configuration
    ports:
      # Port to listen on for HTTP requests
      http: 31000

      # Port to listen on for SRT streams
      srt: 31000

  # Recorder configuration
  recorder:
    # Time after which a stream will be stopped if no connections are made
    timeout: PT1M

    # Time window to search for event instances around the current time
    window: PT1H

  # Configuration of the emiarchive service
  emiarchive:
    # Configuration of the S3 API of the emiarchive service
    s3:
      # Whether to use secure connection with the S3 API
      secure: false

      # Host of the S3 API
      host: emiarchive.emiarchive.svc.cluster.local

      # Port of the S3 API
      port: 30000

      # User to authenticate with the S3 API
      user: readwrite

      # Password to authenticate with the S3 API
      password: password

      # Name of the bucket to use for uploads
      bucket: live

  # Configuration of the emishows service
  emishows:
    # Configuration of the HTTP API of the emishows service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emishows.emishows.svc.cluster.local

      # Port of the HTTP API
      port: 35000

      # Path of the HTTP API
      path: ""

# Configuration of the service
service:
  # Ports configuration
  ports:
    # Port to listen on for HTTP requests
    http: 31000

    # Port to listen on for SRT streams
    srt: 31000
