# Configuration of the obsidian database
obsidian:
  # Configuration of the server
  server:
    # Port to listen on
    port: 20110

  # Credentials for the database
  credentials:
    # Credentials for the main user
    user:
      # Password of the main user
      password: password

# Configuration of the service
service:
  # Port to listen on
  port: 20110
