# Version of Helm this chart is compatible with
apiVersion: v2

# Version of the chart itself
version: "0.6.1"

# Version of the database provided by this chart
appVersion: "0.10.0"

# Name of the chart
name: datatimes

# A short description of the chart
description: Emission times database 🕒

# Home page of the database
home: https://radio-aktywne.github.io/database-datatimes

# Source code repository of the database
sources:
  - https://github.com/radio-aktywne/database-datatimes
