# Configuration of the scorpion service
scorpion:
  # Configuration of clients
  clients:
    # Configuration of OIDC Debugger client
    oidcdebugger:
      # Allowed CORS origins
      allowed_cors_origins:
        - https://oidcdebugger.com

      # Client ID
      client_id: oidcdebugger

      # Client name
      client_name: OIDC Debugger

      # Client URI
      client_uri: https://oidcdebugger.com

      # Allowed grant types
      grant_types:
        - authorization_code
        - refresh_token

      # Allowed redirect URIs
      redirect_uris:
        - https://oidcdebugger.com/debug

      # Allowed response types
      response_types:
        - code

      # Allowed scopes
      scope: openid profile email offline_access

      # Token endpoint authentication method
      token_endpoint_auth_method: none

  # Configuration of crocus app
  crocus:
    # Configuration of public site of crocus app
    public:
      # Host of public site
      host: localhost

      # Path of public site
      path: null

      # Port of public site
      port: 20020

      # Scheme of public site
      scheme: http

  # Enable debug mode
  debug: true

  # Configuration of diamond database
  diamond:
    # Configuration of SQL API of diamond database
    sql:
      # Host of SQL API
      host: diamond.diamond.svc.cluster.local

      # Password to authenticate with SQL API
      password: password

      # Port of SQL API
      port: 20010

  # Configuration of janitor
  janitor:
    # Retention period
    retention: 720h

  # Configuration of lifetimes
  lifetimes:
    # Configuration of token lifetimes
    tokens:
      # Access token lifetime
      access: 1h

      # Refresh token lifetime
      refresh: 720h

  # Configuration of secrets
  secrets:
    # Cookie secrets
    cookie:
      - secretsecretsecret

    # System secrets
    system:
      - secretsecretsecret

  # Configuration of server
  server:
    # Configuration of server ports
    ports:
      # Port for admin traffic
      admin: 20001

      # Port for public traffic
      public: 20000

  # Configuration of URLs
  urls:
    # Admin URL
    admin: http://localhost:20001

    # Issuer URL
    issuer: http://localhost:20000

    # Public URL
    public: http://localhost:20000

# Configuration of the service
service:
  # Ports to listen on
  ports:
    # Port to listen on for admin traffic
    admin: 20001

    # Port to listen on for public traffic
    public: 20000
