# Configuration of the app
app:
  # Configuration of the server
  server:
    # SRT configuration
    srt:
      # Port to listen on
      port: 9000

    # HTTP configuration
    http:
      # Port to listen on
      port: 9001

  # Configuration of the emicast service
  emicast:
    # Configuration of the ICY API of the emicast service
    icy:
      # Host of the ICY API
      host: emicast.emicast.svc.cluster.local

      # Port of the ICY API
      port: 8000

      # User to authenticate with the ICY API
      user: source

      # Password to authenticate with the ICY API
      password: password

      # Mount point to send audio to
      mount: /radio.mp3

  # Configuration of the emitunes service
  emitunes:
    # Configuration of the HTTP API of the emitunes service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emitunes.emitunes.svc.cluster.local

      # Port of the HTTP API
      port: 42000

      # Path of the HTTP API
      path: ""

# Configuration of the service
service:
  # Ports to listen on
  ports:
    # Port to listen on for SRT connections
    srt: 9000

    # Port to listen on for HTTP requests
    http: 9001
