# Configuration of the jasmine app
jasmine:
  # Configuration of APIs
  apis:
    # Configuration of the beaver API
    beaver:
      # Host of the API
      host: beaver.beaver.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10500

      # Scheme of the API
      scheme: http

    # Configuration of the icanhazdadjoke API
    icanhazdadjoke:
      # Host of the API
      host: icanhazdadjoke.com

      # Path of the API
      path: null

      # Port of the API
      port: null

      # Scheme of the API
      scheme: https

    # Configuration of the numbat API
    numbat:
      # Host of the API
      host: numbat.numbat.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10600

      # Scheme of the API
      scheme: http

  # Enable debug mode
  debug: true

  # Configuration of the server
  server:
    # Port to listen on
    port: 10620

# Configuration of the service
service:
  # Port to listen on
  port: 10620
