# Configuration of the tulip app
tulip:
  # Configuration of APIs
  apis:
    # Configuration of the beaver API
    beaver:
      # Host of the API
      host: beaver.beaver.svc.cluster.local

      # Path of the API
      path: null

      # Port of the API
      port: 10500

      # Scheme of the API
      scheme: http

    # Configuration of the icanhazdadjoke API
    icanhazdadjoke:
      # Host of the API
      host: icanhazdadjoke.com

      # Path of the API
      path: null

      # Port of the API
      port: null

      # Scheme of the API
      scheme: https

  # Enable debug mode
  debug: true

  # Configuration of the server
  server:
    # Port to listen on
    port: 10530

# Configuration of the service
service:
  # Port to listen on
  port: 10530
