# Version of Helm this chart is compatible with
apiVersion: v2

# Version of the chart itself
version: "0.9.0"

# Version of the service provided by this chart
appVersion: "0.10.0"

# Name of the chart
name: quokka

# A short description of the chart
description: Broadcast Icecast transmitting ❄️

# Home page of the service
home: https://radio-aktywne.github.io/quokka

# Source code repository of the service
sources:
  - https://github.com/radio-aktywne/quokka
