# Configuration of the app
app:
  # Configuration of the server
  server:
    # Port to listen on
    port: 13000

  # Events configuration
  events:
    # Time window to search for event instances around the current time
    window: PT1H

  # Emishows configuration
  emishows:
    # Configuration of the HTTP API of the emishows service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emishows.emishows.svc.cluster.local

      # Port of the HTTP API
      port: 35000

      # Path of the HTTP API
      path: ""

  # Emistream configuration
  emistream:
    # Configuration of the HTTP API of the emistream service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emistream.emistream.svc.cluster.local

      # Port of the HTTP API
      port: 10000

      # Path of the HTTP API
      path: ""

    # Configuration of the SRT stream of the emistream service
    srt:
      # Host of the SRT stream
      host: emistream.emistream.svc.cluster.local

      # Port of the SRT stream
      port: 10000

  # Emipass configuration
  emipass:
    # Configuration of the HTTP API of the emipass service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emipass.emipass.svc.cluster.local

      # Port of the HTTP API
      port: 11000

      # Path of the HTTP API
      path: ""

    # Configuration of the WHIP API of the emipass service
    whip:
      # Scheme of the WHIP API
      scheme: http

      # Host of the WHIP API
      host: emipass.emipass.svc.cluster.local

      # Port of the WHIP API
      port: 11001

      # Path of the WHIP API
      path: ""

# Configuration of the service
service:
  # Port to listen on
  port: 13000
