# Version of Helm this chart is compatible with
apiVersion: v2

# Version of the chart itself
version: "0.2.1"

# Version of the app provided by this chart
appVersion: "0.2.0"

# Name of the chart
name: aster

# A short description of the chart
description: Broadcast composing app 🧼

# Home page of the app
home: https://radio-aktywne.github.io/aster

# Source code repository of the app
sources:
  - https://github.com/radio-aktywne/aster
