# Version of Helm this chart is compatible with
apiVersion: v2

# Version of the chart itself
version: "0.1.3"

# Version of the database provided by this chart
appVersion: "0.5.0"

# Name of the chart
name: emitimes

# A short description of the chart
description: Emission times 🕒

# Home page of the database
home: https://radio-aktywne.github.io/database-emitimes

# Source code repository of the database
sources:
  - https://github.com/radio-aktywne/database-emitimes
