# Configuration of the app
app:
  # Configuration of the server
  server:
    # Port to listen on
    port: 33000

  # Stream configuration
  stream:
    # Timeout for trying to reserve a stream
    timeout: PT1H

  # Cleaner configuration
  cleaner:
    # Reference datetime for cleaning
    reference: 2000-01-01T00:00:00

    # Interval between cleanings
    interval: P1D

  # Synchronizer configuration
  synchronizer:
    # Reference datetime for synchronization
    reference: 2000-01-01T00:00:00

    # Interval between synchronizations
    interval: PT1M

    # Stream synchronizer configuration
    stream:
      # Duration of the time window
      window: P1D

  # Configuration of the emishows service
  emishows:
    # Configuration of the HTTP API of the emishows service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emishows.emishows.svc.cluster.local

      # Port of the HTTP API
      port: 35000

      # Path of the HTTP API
      path: ""

  # Configuration of the datarecords database
  datarecords:
    # Configuration of the S3 API of the datarecords database
    s3:
      # Whether to use secure connection with the S3 API
      secure: false

      # Host of the S3 API
      host: datarecords.datarecords.svc.cluster.local

      # Port of the S3 API
      port: 30000

      # User to authenticate with the S3 API
      user: readonly

      # Password to authenticate with the S3 API
      password: password

      # Buckets configuration
      buckets:
        # Name of the bucket with recordings of live events
        live: live

        # Name of the bucket with prerecorded events
        prerecorded: prerecorded

  # Configuration of the emistream service
  emistream:
    # Configuration of the HTTP API of the emistream service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emistream.emistream.svc.cluster.local

      # Port of the HTTP API
      port: 10000

      # Path of the HTTP API
      path: ""

    # Configuration of the SRT stream of the emistream service
    srt:
      # Host of the SRT stream
      host: emistream.emistream.svc.cluster.local

      # Port of the SRT stream
      port: 10000

# Configuration of the service
service:
  # Port to listen on
  port: 33000
