# Configuration of the app
app:
  # Configuration of the server
  server:
    # Port to listen on
    port: 33000

  # Operations configuration
  operations:
    # Stream operation configuration
    stream:
      # Timeout for trying to reserve a stream
      timeout: PT1H

      # Duration of the time window for searching for past records
      window: P60D

  # Cleaner configuration
  cleaner:
    # Reference datetime for cleaning
    reference: 2000-01-01T00:00:00

    # Interval between cleanings
    interval: P1D

  # Synchronizer configuration
  synchronizer:
    # Reference datetime for synchronization
    reference: 2000-01-01T00:00:00

    # Interval between synchronizations
    interval: PT1M

    # Synchornizers configuration
    synchronizers:
      # Stream synchronizer configuration
      stream:
        # Duration of the time window
        window: P1D

  # Configuration of the emilounge service
  emilounge:
    # Configuration of the HTTP API of the emilounge service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emilounge.emilounge.svc.cluster.local

      # Port of the HTTP API
      port: 28000

      # Path of the HTTP API
      path: ""

  # Configuration of the emirecords service
  emirecords:
    # Configuration of the HTTP API of the emirecords service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emirecords.emirecords.svc.cluster.local

      # Port of the HTTP API
      port: 31000

      # Path of the HTTP API
      path: ""

  # Configuration of the emishows service
  emishows:
    # Configuration of the HTTP API of the emishows service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emishows.emishows.svc.cluster.local

      # Port of the HTTP API
      port: 35000

      # Path of the HTTP API
      path: ""

  # Configuration of the emistream service
  emistream:
    # Configuration of the HTTP API of the emistream service
    http:
      # Scheme of the HTTP API
      scheme: http

      # Host of the HTTP API
      host: emistream.emistream.svc.cluster.local

      # Port of the HTTP API
      port: 10000

      # Path of the HTTP API
      path: ""

    # Configuration of the SRT stream of the emistream service
    srt:
      # Host of the SRT stream
      host: emistream.emistream.svc.cluster.local

      # Port of the SRT stream
      port: 10000

# Configuration of the service
service:
  # Port to listen on
  port: 33000
